### ISSUE TITLE
<set>:1: error: value / is not a member of object sbt.ThisBuild

### ISSUE THREAD

**Issue by tthyer** [ShiftLeftSecurity/sbt-ci-release-early#1]
I ran into a problem while evaluating sbt-ci-release-early. After following the recommended setup in the README, I kept seeing this sort of error:
```
 * [new tag]         v0.1.9 -> v0.1.9
<set>:1: error: value / is not a member of object sbt.ThisBuild
ThisBuild/version := "0.1.9"
         ^
[error] Type error in expression
```
It required a combination of looking at your most recent commits and stumbling across sbt's advice on migrating to slash usage to make me realize that the problem was that my version of sbt, 1.0.4, was a bit too far behind. After upgrading to 1.2.8, sbt-ci-release-early works fine. Is it possible for you to warn what the lowest required version is during execution?
